version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521:xe
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      db:
        condition: service_healthy

  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracledb
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: rootpassword
      APP_USER: app_user
      APP_USER_PASSWORD: app_password
    volumes:
      - ./init.sql:/container-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/rootpassword@localhost:1521/xe || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
