-- Create a user for the application
CREATE USER app_users IDENTIFIED BY app_password;
GRANT CONNECT, RESOURCE TO app_users;
ALTER USER app_users QUOTA UNLIMITED ON USERS; -- Grant privileges to use the USERS tablespace

-- Create the roles table
CREATE TABLE app_users.role (
                                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                name VARCHAR2(50) NOT NULL
);

-- Create the app_user table
CREATE TABLE app_users.app_user ( -- Renamed table
                                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                    login VARCHAR2(100) UNIQUE NOT NULL,
                                    password VARCHAR2(255) NOT NULL,
                                    active NUMBER(1) DEFAULT 1 NOT NULL
);

-- Create the user_roles table
CREATE TABLE app_users.user_roles (
                                      user_id NUMBER NOT NULL,
                                      role_id NUMBER NOT NULL,
                                      PRIMARY KEY (user_id, role_id),
                                      FOREIGN KEY (user_id) REFERENCES app_users.app_user (id),
                                      FOREIGN KEY (role_id) REFERENCES app_users.role (id)
);

-- Insert initial data
INSERT INTO app_users.role (name) VALUES ('ROLE_USER');
INSERT INTO app_users.role (name) VALUES ('ROLE_ADMIN');
