name: Trigger Jenkins Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger-jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug information
        run: |
          echo "Docker version:"
          docker --version
          echo "Docker info:"
          docker info
          echo "Current user:"
          whoami
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Trigger Jenkins Build
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          echo "Fetching Jenkins crumb..."
          CRUMB=$(curl -s -u "${JENKINS_USER}:${JENKINS_API_TOKEN}" "${JENKINS_URL}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          
          if [ -z "$CRUMB" ]; then
            echo "Failed to obtain Jenkins crumb. Check your Jenkins configuration and credentials."
            exit 1
          fi
          
          echo "Triggering Jenkins job..."
          RESPONSE=$(curl -s -X POST \
            -u "${JENKINS_USER}:${JENKINS_API_TOKEN}" \
            -H "$CRUMB" \
            "${JENKINS_URL}/job/Security-Pro/buildWithParameters" \
            --data-urlencode "GITHUB_SHA=${{ github.sha }}" \
            --data-urlencode "GITHUB_REF=${{ github.ref }}")
          
          if [[ $RESPONSE == *"Error"* ]]; then
            echo "Failed to trigger Jenkins job. Response: $RESPONSE"
            exit 1
          else
            echo "Jenkins job triggered successfully!"
          fi

