name: Jenkins CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  trigger-jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Jenkins Build
        run: |
          # First, attempt to get the crumb
          CRUMB=$(curl -s "http://localhost:8080/crumbIssuer/api/xml" | grep -oP '(?<=<crumb>).*?(?=</crumb>)')
          
          # Trigger Jenkins job with crumb
          curl -X POST \
          -H "Jenkins-Crumb:$CRUMB" \
          "http://localhost:8080/job/Security-Pro/build" \
          --data-urlencode json='{
            "parameter": [
              {"name":"GITHUB_SHA", "value":"'"${{ github.sha }}"'"},
              {"name":"GITHUB_REF", "value":"'"${{ github.ref }}"'"}
            ]
          }'